appPort: 8080
managementPort: 8082
basePath: /api
serviceAccountName: observatory-api-workload-identity
health:
  livenessPath: /health/liveness
  readinessPath: /health/readiness
resources:
  requests:
    cpu: 5m
    memory: 64Mi
  limits:
    cpu: null
    memory: 128Mi
